name: ChatChannelManager
main: com.github.sirkarpfen.chatchannel.ChatChannelManager
depend: [ PermissionsEx ]
version: 1.19.1
authors: [t3hk0d3, sirkarpfen]
website: www.secretcraft.de
description: Chat Management plugin for PermissionsEx
commands:
  channel:
    description: Wechselt den Channel mit /channel <Channel> und listet alle Spieler im Channel auf mit /channel list