name: ChatManager
main: ru.tehkode.chatmanager.bukkit.ChatManager
depend: [ PermissionsEx ]
version: 1.19.1
author: t3hk0d3
website: www.bukkit.org
description: Chat management plugin for PermissionsEx
commands:
  channel:
    description: Wechselt den "Channel" mit /channel <Channel> und listet alle Spieler im Channel auf mit: /channel list
    permission-message: You do not have the Permission to use this Command.
    usage: Beispiele:
           /channel global für den Channel: Global
           /channel lokal für den Channel: Lokal
           /channel handel für den Channel: Handel