name: ChatManager
main: ru.tehkode.chatmanager.bukkit.ChatManager
depend: [ PermissionsEx ]
version: 1.19.1
author: t3hk0d3
website: www.bukkit.org
description: Chat management plugin for PermissionsEx
commands:
  global:
    description: Wechselt in den Global-Channel.
    permission-message: You do not have the Permission to use this Command.
    usage: "Richtige Schreibweise: /global"
  lokal:
    description: Wechselt in den Lokal-Channel.
    permission-message: You do not have the Permission to use this Command.
    usage: "Richtige Schreibweise: /lokal"
  team:
    description: Wechsel in den Team-Channel.
    permission-message: You do not have the Permission to use this Command.
    usage: "Richtige Schreibweise: /team"
  handel:
    description: Wechsel in den Handel-Channel.
    permission-message: You do not have the Permission to use this Command.
    usage: "Richtige Schreibweise: /handel"
  channel:
    description: Zeigt an wer sich in dem Channel befindet.
    permission-message: You do nat have the Permission to use this Command.
    usage: "Richtige Schreibweise: /channel list"